namespace Titan.Platform.Win32.D3D;

[Flags]
public enum D3D_COMPILE_FLAGS
{
    D3DCOMPILE_DEBUG = (1 << 0),
    D3DCOMPILE_SKIP_VALIDATION = (1 << 1),
    D3DCOMPILE_SKIP_OPTIMIZATION = (1 << 2),
    D3DCOMPILE_PACK_MATRIX_ROW_MAJOR = (1 << 3),
    D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR = (1 << 4),
    D3DCOMPILE_PARTIAL_PRECISION = (1 << 5),
    D3DCOMPILE_FORCE_VS_SOFTWARE_NO_OPT = (1 << 6),
    D3DCOMPILE_FORCE_PS_SOFTWARE_NO_OPT = (1 << 7),
    D3DCOMPILE_NO_PRESHADER = (1 << 8),
    D3DCOMPILE_AVOID_FLOW_CONTROL = (1 << 9),
    D3DCOMPILE_PREFER_FLOW_CONTROL = (1 << 10),
    D3DCOMPILE_ENABLE_STRICTNESS = (1 << 11),
    D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY = (1 << 12),
    D3DCOMPILE_IEEE_STRICTNESS = (1 << 13),
    D3DCOMPILE_OPTIMIZATION_LEVEL0 = (1 << 14),
    D3DCOMPILE_OPTIMIZATION_LEVEL1 = 0,
    D3DCOMPILE_OPTIMIZATION_LEVEL2 = ((1 << 14) | (1 << 15)),
    D3DCOMPILE_OPTIMIZATION_LEVEL3 = (1 << 15),
    D3DCOMPILE_RESERVED16 = (1 << 16),
    D3DCOMPILE_RESERVED17 = (1 << 17),
    D3DCOMPILE_WARNINGS_ARE_ERRORS = (1 << 18),
    D3DCOMPILE_RESOURCES_MAY_ALIAS = (1 << 19),
    D3DCOMPILE_ENABLE_UNBOUNDED_DESCRIPTOR_TABLES = (1 << 20),
    D3DCOMPILE_ALL_RESOURCES_BOUND = (1 << 21),
    D3DCOMPILE_DEBUG_NAME_FOR_SOURCE = (1 << 22),
    D3DCOMPILE_DEBUG_NAME_FOR_BINARY = (1 << 23),
}
