version: "3.9"
services:
  build-engine:
    image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    command: >
      dotnet build --configuration Release
    volumes: 
      - .:/source
    working_dir: /source  
    
  unit-test:
    image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    command: dotnet test
    volumes: 
      - .:/source
    working_dir: /source
