namespace Titan.Windows.Win32;

public enum HID_USAGE : ushort
{
    HID_USAGE_GENERIC_POINTER = 0x01,
    HID_USAGE_GENERIC_MOUSE = 0x02,
    HID_USAGE_GENERIC_JOYSTICK = 0x04,
    HID_USAGE_GENERIC_GAMEPAD = 0x05,
    HID_USAGE_GENERIC_KEYBOARD = 0x06,
    HID_USAGE_GENERIC_KEYPAD = 0x07,
    HID_USAGE_GENERIC_MULTI_AXIS_CONTROLLER = 0x08,
    HID_USAGE_GENERIC_TABLET_PC_SYSTEM_CTL = 0x09,
    HID_USAGE_GENERIC_PORTABLE_DEVICE_CONTROL = 0x0D,
    HID_USAGE_GENERIC_INTERACTIVE_CONTROL = 0x0E,
    HID_USAGE_GENERIC_COUNTED_BUFFER = 0x3A,
    HID_USAGE_GENERIC_SYSTEM_CTL = 0x80
}
