namespace Titan.Platform.Win32.Win32;

public enum HID_USAGE_PAGE : ushort
{
    HID_USAGE_PAGE_UNDEFINED = 0x00,
    HID_USAGE_PAGE_GENERIC = 0x01,
    HID_USAGE_PAGE_SIMULATION = 0x02,
    HID_USAGE_PAGE_VR = 0x03,
    HID_USAGE_PAGE_SPORT = 0x04,
    HID_USAGE_PAGE_GAME = 0x05,
    HID_USAGE_PAGE_GENERIC_DEVICE = 0x06,
    HID_USAGE_PAGE_KEYBOARD = 0x07,
    HID_USAGE_PAGE_LED = 0x08,
    HID_USAGE_PAGE_BUTTON = 0x09,
    HID_USAGE_PAGE_ORDINAL = 0x0A,
    HID_USAGE_PAGE_TELEPHONY = 0x0B,
    HID_USAGE_PAGE_CONSUMER = 0x0C,
    HID_USAGE_PAGE_DIGITIZER = 0x0D,
    HID_USAGE_PAGE_HAPTICS = 0x0E,
    HID_USAGE_PAGE_PID = 0x0F,
    HID_USAGE_PAGE_UNICODE = 0x10,
    HID_USAGE_PAGE_ALPHANUMERIC = 0x14,
    HID_USAGE_PAGE_SENSOR = 0x20,
    HID_USAGE_PAGE_LIGHTING_ILLUMINATION = 0x59,
    HID_USAGE_PAGE_BARCODE_SCANNER = 0x8C,
    HID_USAGE_PAGE_WEIGHING_DEVICE = 0x8D,
    HID_USAGE_PAGE_MAGNETIC_STRIPE_READER = 0x8E,
    HID_USAGE_PAGE_CAMERA_CONTROL = 0x90,
    HID_USAGE_PAGE_ARCADE = 0x91,
    HID_USAGE_PAGE_MICROSOFT_BLUETOOTH_HANDSFREE = 0xFFF3,
    HID_USAGE_PAGE_VENDOR_DEFINED_BEGIN = 0xFF00,
    HID_USAGE_PAGE_VENDOR_DEFINED_END = 0xFFFF
}
