namespace Titan.Assets
{
    // TODO: this should be generated by the source generator, but it mess up the IDE coloring so I've disabled it.
    public enum AssetTypes
    {
        VertexShader, 
        PixelShader, 
        Texture, 
        Model, 
        Material,
        Atlas,
        Font,
        Count
    }
}
