namespace Titan.Platform.Win32.D3D12;

public struct D3D12_RENDER_PASS_ENDING_ACCESS
{
    public D3D12_RENDER_PASS_ENDING_ACCESS_TYPE Type;
    public D3D12_RENDER_PASS_ENDING_ACCESS_RESOLVE_PARAMETERS Resolve;
}