namespace Titan.Platform.Win32.D3D12;

public struct D3D12_RENDER_PASS_BEGINNING_ACCESS
{
    public D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE Type;
    public D3D12_RENDER_PASS_BEGINNING_ACCESS_CLEAR_PARAMETERS Clear;
}