name: Titan

on: push

jobs:
  package-assets:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install .NET 7.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Build packager
      run: dotnet build tools/Titan.Tools.Packager -c Shipping

    - name: Package assets
      run: |
        dotnet run --project tools/Titan.Tools.Packager -c Shipping -- package -m samples\Titan.Sandbox\assets\anothermanifest.tmanifest -o release/ -g samples\Titan.Sandbox -n Titan.Sandbox
        dotnet run --project tools/Titan.Tools.Packager -c Shipping -- package -m samples\Titan.Sandbox\assets\sample_01.tmanifest -o release/ -g samples\Titan.Sandbox -n Titan.Sandbox

    # this step should be replaced with a proper build tool that will package the build
    - name: Package game
      run: dotnet publish samples/Titan.Sandbox -c Shipping -o release/ -r win-x64 --self-contained true -p:PublishTrimmed=True -p:PublishAot=True -p:DebugType=None -p:DebugSymbols=false

    - name: Upload Game
      uses: actions/upload-artifact@v3
      with:
        name: Titan.Sandbox
        path: release/


