name: Titan

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install .NET 7.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
        
    - name: Build Engine
      run: dotnet build src/Titan/Titan.csproj -c Shipping
    
    - name: Build Tools
      run: |
        dotnet build tools/Titan.Tools.ManifestBuilder/Titan.Tools.ManifestBuilder.csproj -c Shipping
        dotnet build tools/Titan.Tools.Packager/Titan.Tools.Packager.csproj -c Shipping

    - name: Test
      run: dotnet test
