namespace Titan.Platform.Win32.DBT;

[Flags]
public enum DEVICE_NOTIFY_FLAGS
{
    DEVICE_NOTIFY_WINDOW_HANDLE = 0x0,
    DEVICE_NOTIFY_SERVICE_HANDLE = 0x1,
    DEVICE_NOTIFY_ALL_INTERFACE_CLASSES = 0x4
}
